### ISSUE TITLE
Cannot run ozone_demo on RPi 3B+

### ISSUE THREAD

**Issue by EwanRoycroft** [bbc/chromium#10]
### Description
Builds of the `ozone_demo` target will exit after a few seconds, reporting a seg fault.

### More information
| Attribute | Value |
| --- | --- |
| **Version** | 86.0.4205.0 (32-bit) |
| **Build** | Debug, release |
| **Platform** | Ozone-GBM |
| **Target** | `ozone_demo` |
| **Device** | Raspberry Pi 3B+ |
| **OS** | Raspbian 10 "buster" |
| **Kernel** | 5.4.51-v7+ |

### Steps to reproduce
Make a build of `ozone_demo` for the Ozone-GBM platform and run on the RPi 3B+.

#### GN arguments
(Ignoring any additional release/codec args.)
```
use_ozone = true
ozone_platform_x11 = false
ozone_platform_gbm = true
ozone_platform_headless = false
use_vc4_minigbm = true

ffmpeg_branding = "Chrome"
proprietary_codecs = true

target_os = "chromeos"
target_cpu = "arm"
use_sysroot = true
target_sysroot = "//build/linux/debian_sid_arm-sysroot"

google_api_key = "no"
google_default_client_id = "no"
google_default_client_secret = "no"

enable_nacl = false
blink_symbol_level = 0
```

#### Command
```shell
EGL_PLATFORM=surfaceless ./ozone_demo --ozone-platform=gbm
```

### Terminal output
```
minigbm: vc4_init
sd-device-enumerator: Scan all dirs
sd-device-enumerator: Scanning /sys/bus
sd-device-enumerator: Scanning /sys/class
[0827/122919.237290:WARNING:gbm_surface_factory.cc(115)] Platform device extensions not found.
minigbm: vc4_init
minigbm: vc4_bo_create_with_modifiers, format=XR24
minigbm: vc4_bo_create_for_modifier, format=XR24
minigbm: vc4_bo_map
minigbm: vc4_bo_create_with_modifiers, format=AR24
minigbm: vc4_bo_create_for_modifier, format=AR24
minigbm: vc4_bo_create_with_modifiers, format=AR24
minigbm: vc4_bo_create_for_modifier, format=AR24
sd-device-enumerator: Scan all dirs
sd-device-enumerator: Scanning /sys/bus
sd-device-enumerator: Scanning /sys/class
Received signal 11 SEGV_MAPERR 000000000000
#0 0x000000877606 base::debug::CollectStackTrace()
#1 0x000000846d18 base::debug::StackTrace::StackTrace()
#2 0x000000877586 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x000076c94130 (/lib/arm-linux-gnueabihf/libc-2.28.so+0x2d12f)
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

### gdb backtrace
```
#0  0x00000000 in ?? ()
#1  0x74bacc36 in rx::FramebufferGL::syncState(gl::Context const*, unsigned int, angle::BitSetT<31u, unsigned int, unsigned int> const&) ()
   from /home/pi/chromium/dev/src/out/Ozone_ARM_V4L2_Release/libGLESv2.so
#2  0x74b1c4a2 in gl::Framebuffer::checkStatusImpl(gl::Context const*) const () from /home/pi/chromium/dev/src/out/Ozone_ARM_V4L2_Release/libGLESv2.so
#3  0x74b77a28 in gl::ValidateClear(gl::Context const*, unsigned int) () from /home/pi/chromium/dev/src/out/Ozone_ARM_V4L2_Release/libGLESv2.so
#4  0x74ad59d8 in gl::Clear(unsigned int) () from /home/pi/chromium/dev/src/out/Ozone_ARM_V4L2_Release/libGLESv2.so
#5  0x00569344 in ui::SurfacelessGlRenderer::RenderFrame() ()
#6  0x007ad45c in base::TaskAnnotator::RunTask(char const*, base::PendingTask*) ()
#7  0x007b6452 in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*) ()
#8  0x007b6220 in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ()
#9  0x007b672c in non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ()
#10 0x007cfc8c in base::MessagePumpLibevent::Run(base::MessagePump::Delegate*) ()
#11 0x007b68c8 in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ()
#12 0x007a9296 in base::RunLoop::Run() ()
#13 0x00567ffa in main ()
```

**Comment by EwanRoycroft** [comment]
This does not occur in versions 84.0.4147.141, 86.0.4240.175, or 88.0.4305.0
